language: node_js
env:
  matrix:
    - NODE_VERSION=8
    - NODE_VERSION=10
cache:
  directories:
  - node_modules
before_install:
- nvm install $NODE_VERSION
- node --version
- python --version
install:
- npm install
- npm install -g coveralls nyc
script:
- npm run test:coverage
after_success:
- nyc report --reporter=text-lcov | coveralls
notifications:
  email:
    on_success: never
    on_failure: change